apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: hello-world
      version: "0.1.3"
      sourceRef:
        kind: HelmRepository
        name: technicityworks
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: aanogueira/hello-world # {"$imagepolicy": "flux-system:hello-world:name"}
      tag: 0.0.1 # {"$imagepolicy": "flux-system:hello-world:tag"}
